<?php

namespace Modules\DiagnosticCentre\Database\Seeders;

use App\Models\User;
use Faker\Factory;
use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Str;
use Modules\DiagnosticCentre\Entities\Item;
use Modules\DiagnosticCentre\Services\ItemsService;

class ItemsTableSeeder extends Seeder
{
    protected $itemsService;

    public function __construct()
    {
        $this->itemsService = new ItemsService(); 
    }
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Factory::create();

        $items_data = ([
            [  
                'name'          => Str::ucfirst('ACID PHOSPHATE (Prostate)'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => 1199,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ALBUMIN'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('B/S 1.5 Hrs.ABF'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CHOLESTEROL'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CREATININE OF PERITONEAL FLUID'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => 600,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('JOINT FLUID BIO-CHEM'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('SAAG (Ascitic Fluid Albumin+Serum Albumin)'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('URINE CAL.24hrs.'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('URINE URIC ACID (SPOT)'),
                'category_id'   => 4,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => 500,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('BLOOD FILM'),
                'category_id'   => 5,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => 750,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CBC'),
                'category_id'   => 5,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('TC DC ESR'),
                'category_id'   => 5,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PLATELET COUNT'),
                'category_id'   => 5,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('L.E CELLS'),
                'category_id'   => 5,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('A.FETO PROTEIN'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Anti Ds DNA'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Anti-Eardiolipin AB'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Anti-HBe/HBeAb/A-HBeAg'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('B-HCG'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Anti-Thyroglobulin'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('C1 Estrease Inhibitor (not in dlab)'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CHIKUN GUNYA'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Dengue NS1 Ag'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('DENGUE VIRUS ab IgG'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('HBeAg'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Herpes Simplex Virus Type 2 Ab IgM'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('SERUM INSULIN (R)'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('TB-IgA.IgM.IgG'),
                'category_id'   => 6,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PCR BACTERIAL MENINGITIS PANEL'),
                'category_id'   => 7,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PCR BACTERIAL PANEL'),
                'category_id'   => 7,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PCR HCV RNA GENOTYPING (Real Time PCR)'),
                'category_id'   => 7,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PCR MTB DNA/ GENE XPERT (pus, Ascitic Fluid, lymph node aspirate, peritonial fluid, bone marrow )'),
                'category_id'   => 7,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PCR MENINGITIS MULTIPLEX TEST'),
                'category_id'   => 7,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PCR VIRAL PANEL-2'),
                'category_id'   => 7,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRA BRAIN'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRCP'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRI ANGIOGRAPHY'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRI BRAIN & BASE OF SKULL'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRI D.Spine + C.Spine'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRI HUMERUS INCLODING RADIUS & ULNA'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRI LOWER ABDOMEN'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRI KNEE JOINT'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('MRI THORACIC SPINE & SCREENING'),
                'category_id'   => 8,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('BRONCHOSCOPY'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Portable X-ray'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('XR ANKLE (BOTH) JT B/V DIGITAL'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('XR BOTH ELBOW JT. DIGITAL'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('XR BOTH KNEE JT. B/V DIGITAL'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('XR BOTH WRIST JT. B/V DIGITAL'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('XR C/SPINE AP/LAT.B.OBLIQUE DIGITAL'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('XR FEMER\THIGH B\V'),
                'category_id'   => 9,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CT 3D IMAGING'),
                'category_id'   => 10,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CT ABDOMEN ANGIOGRAM'),
                'category_id'   => 10,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CT ANGIO CALCIUM SCORE'),
                'category_id'   => 10,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CT CHEST'),
                'category_id'   => 10,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CT FOREARM RT./LT.'),
                'category_id'   => 10,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CT SCAN KUB (NON CONTRAST) with report'),
                'category_id'   => 10,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CT WHOLE ABDOMEN'),
                'category_id'   => 10,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('LIVER BIOPSY (USG guided)'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('USG ABD. MCC & PVR'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('USG BIOPHYSICAL PROFILE WITH COLOR DOPLER'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('USG CD OF VERTEBRO-BASILA'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('USG HBS+ Pelvic Organs'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('USG HBS+KUB+PVR & Pelvic Organs'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('USG MCC + PVR'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('USG Musculoskeletal'),
                'category_id'   => 11,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ECG'),
                'category_id'   => 12,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ECG OUTSIDE'),
                'category_id'   => 12,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ECG (12 LEAD)'),
                'category_id'   => 12,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ETT'),
                'category_id'   => 13,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Balloon Dilatation (Penumatic) Achalasia'),
                'category_id'   => 15,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Balloon Dilatation (Penumatic) Achalasia'),
                'category_id'   => 15,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('COLONOSCOPY(Full)'),
                'category_id'   => 15,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Heamostasis Ulcer Bleeding Heamoclip'),
                'category_id'   => 15,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PROSTATE BIOPSY'),
                'category_id'   => 15,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('DUODENAL DILATION(BALLOON)'),
                'category_id'   => 15,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Ascitic Fluid Anaerobic C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ASCITIC FLUID C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Aural Swab Anaerobic C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('BRONCHEAL WASH Anaerobic C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CON.SWAB Anaerobic C/S(B/E)xxx'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ENDOTRACHEAL TIP Anaerobic C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('PERICARDIAL FLUID Anaerobic C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Semen for Anaerobic C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('TRACHEAL ASPIRATE FOR FUNGUS C/S'),
                'category_id'   => 16,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ASCITIC FLUID CYTOLOGY'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CONJ. SWAB GRAM STAIN LT.'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('CFT KALA AZAR (not in dlab)'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('ENDOCERVICAL SWAB GM STAIN'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('NAIL CLIPPING for Dermatophyte'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('P/S FOR R/E M/E'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('SKIN SCRAPPING for Dermatophyte'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Tracheal Aspirate AFB'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Tracheal Aspirate G.Stain'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('URETHRAL SMEAR R/E M/E(WET FILM+GM STAIN)'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('URINE R/E TEST (Auto Analyzer)'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Urine Urobilinogen'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('URINE R/E M/E'),
                'category_id'   => 17,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Syringe'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Test Tube'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Urine test tube'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Band Aid'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Povisep'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Irrigation Syringe'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Surgical tape'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Dressing Framycetin Gauze'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => null,
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            [  
                'name'          => Str::ucfirst('Sofra-Tulle'),
                'category_id'   => 3,
                'price'         => $faker->numberBetween(280,2000),
                'offer_price'   => null,
                'exp_date'      => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),
                'description'   => $faker->sentence,
                'created_by'    => User::inRandomOrder()->first()->id,
                'created_at'    => $faker->dateTimeBetween('-2 years', 'now', 'UTC'),                
            ],
            
        ]);



        foreach($items_data as $item){
            $code = $this->itemsService->generateItemCode();
            Item::create(array_merge($item, ['code' => $code]));

        }
    }
}
